# Site setings
name: 'George'
description: 'PhD Student'
meta_description: 'Wildlife, Conservation, Genomics'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "Hi there! My name is George. This website is currently under development. Please excuse the mess."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://royce.netlify.com/
#disqus: 'justgoodthemes'
mailchimp_url: 'http://eepurl.com/h2oERL'
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: george.zaragoza@gmail.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'georgeomics'
#facebook: 'username'
github: 'georgeomics'
#codepen: 'username'
#dribbble: 'username'
#medium: '@username'
instagram: 'georgeomics'
#pinterest: 'username'
linkedin: 'georgezaragoza'
#producthunt: '@username'
#quora: 'username'


# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Style Guide
    url: /style-guide
  - text: Science
    url: /science
  - text: Conscience
    url: /conscience
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search
    
# The site navigation can be found in the **_config.yml** file. To add a page to the site navigation simply add your new page in the markdown format (e.g. newpage.md) in the theme root folder. Next edit your navigation menu located in **_config.yml** file on line 37. To add a new item to the navigation you have to add the item name and url. For example:
#~~~~
#navigation:
#- text: New Page
#url: /newpage/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 7
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
